server:
  port: 8888

spring:
  application:
    name: config-server
  autoconfigure:
    exclude: org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration
  cloud:
    config:
      server:
        allow-override: true
        override-none: false
        override-system-properties: true
  profiles:
    active: native  # Включаем native profile

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, refresh
