spring:
  datasource:
    url: jdbc:postgresql://auditorium-postgres:5432/auditorium_service_db
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yml

server:
  port: 8081
  servlet:
    context-path: /

logging:
  level:
    root: info

testcontainers:
  enabled: true