datasource:
  url: jdbc:postgresql://user-postgres:5432/springwa
  username: postgres
  password: postgres
  driverClassName: org.postgresql.Driver
spring:
  datasource:
    url: jdbc:postgresql://user-postgres:5432/springwa
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yml

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: info
